name: Import tokens
on: workflow_dispatch

jobs:
  sync-tokens-to-figma:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Set NPM version
        run: npm install -g npm@9.5.1

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Sync tokens to Figma file
        run: npm run sync-tokens-to-figma
        env:
          TOKENS_FILE_ID: ${{ vars.TOKENS_FILE_ID }}
          PALETTE_FILE_ID: ${{ vars.PALETTE_FILE_ID }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
