name: Export tokens
on: workflow_dispatch

jobs:
  sync-figma-to-tokens:
    runs-on: ubuntu-latest
    permissions:
      # Need to be able to create new branches and commits
      contents: write
      pull-requests: write
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Set NPM version
        run: npm install -g npm@9.5.1

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Sync variables in Figma file to tokens
        run: npm run tokens:import
        env:
          TOKENS_FILE_ID: ${{ vars.TOKENS_FILE_ID }}
          PALETTE_FILE_ID: ${{ vars.PALETTE_FILE_ID }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update tokens from Figma
          title: Update tokens from Figma
          body: 'Update tokens from Figma from file: https://www.figma.com/file/${{ vars.TOKENS_FILE_ID }}'
          branch: update-tokens
