name: Tokens build
on: [push]

jobs:
  tokens-build:
    runs-on: ubuntu-latest
    permissions:
      # Need to be able to create new branches and commits
      contents: write
      pull-requests: write
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Set NPM version
        run: npm install -g npm@9.5.1

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Tokens Build
        run: npm run build
        env:
          TOKENS_FILE_ID: ${{ vars.TOKENS_FILE_ID }}
          PALETTE_FILE_ID: ${{ vars.PALETTE_FILE_ID }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'feat: Update CSS Variables with latest token changes'
          title: Update CSS Variables with latest token changes
          body: 'Update tokens from Figma from file: https://www.figma.com/file/${{ github.event.inputs.file_key }}. Build tokens, and generate CSS Variables, Flutter things, and React Native stuff against Design Token Spec Compliant JSON files.'
          branch: update-tokens
